### ISSUE TITLE
default elementIsScrollable causes infinite update if not set to false

### ISSUE THREAD

**Issue by psimyn** [RealScout/redux-infinite-scroll#1]
Since elementIsScrollable defaults to true (and isn't required), a variable height element causes recursive calls to loadMore (in chrome at least). Since each loadMore changes the size of the scroll container, _elScrollListener keeps getting fired.

Was easy enough to fix by setting elementIsScrollable false, but was a bit unclear at first.

**Comment by dcurletti** [comment]
Thanks for the input @psimyn . I will update the docs to better reflect the differences between window and div scrolling.
