### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by gogoout** [RealScout/redux-infinite-scroll#15]
`ReduxInfiniteScroll is not defined` because you removed script in the index.html due to this commit (https://github.com/RealScout/redux-infinite-scroll/commit/c182dd032fd930bfc80f7928236dfb44254c74cf)

**Comment by dcurletti** [comment]
Unfortunately we never got around to having a functioning demo page. See the readme for usage instructions.

**Comment by shabaz-ejaz** [comment]
@dcurletti Then you should probably remove the demo link if it is not functional.
