### ISSUE TITLE
Allow for scrolling on the x-axis

### ISSUE THREAD

**Issue by dcurletti** [RealScout/redux-infinite-scroll#21]

**Comment by dcurletti** [comment]
X axis.

**Comment by mbrevda** [comment]
Would love this!

**Comment by dcurletti** [comment]
Thanks to @mrkvngrkn for the PR, should get this published later today. @mbrevda

**Comment by mbrevda** [comment]
I've taken to using https://github.com/bvaughn/react-virtualized, which provides similar functionality. It's a great lib, so if you ever get tired of maintaining this one, hop on over. On the other hand, I'm sure this is good too, and there is room for many. Either way, thanks for the mention!

**Comment by dcurletti** [comment]
Nice, looks great.
