### ISSUE TITLE
Use efficient rendering (e.g. react-infinite)

### ISSUE THREAD

**Issue by neverfox** [RealScout/redux-infinite-scroll#23]
It's great to see a library like this specifically for redux, but most of what I'm after (and I'd argue, a lot of others too) when using an infinite scroller is also "efficient" rendering, i.e. rendering only the visible rows and perhaps a small pre-/post- buffer. This library (at least based on the examples) renders all fetched rows, even when they're scrolled away. Are there any plans to add this enhancement?

**Comment by dcurletti** [comment]
Hi @neverfox , thanks for checking out this repo! 

Efficient rendering has been considered, but as of right now there are no plans to add this feature.

**Comment by dcurletti** [comment]
I'm going to close this as it has been deemed outside the scope of all future releases.
