### ISSUE TITLE
Usage with Immutable js

### ISSUE THREAD

**Issue by shotaK** [RealScout/redux-infinite-scroll#30]
Is library supposed to work with Immutable js types?

As I see in ReduxInfiniteScroll.jsx file, proptype checking for Immutable types is commented. While `_totalItemsSize` functions still checks for size of immutable types, which in my case caused some problems, when using library with native Javascript arrays.

**Comment by dcurletti** [comment]
Hi @shotaK , yes the library works with Immutable js.  I only commented out the proptype checks.

**Comment by dcurletti** [comment]
I'm going to close for now, but feel free to ask more questions.
