### ISSUE TITLE
New Data replacing current data instead of extend it and LoadMore function only run once

### ISSUE THREAD

**Issue by stefensuhat** [RealScout/redux-infinite-scroll#31]
Container:

    import React, { Component } from 'react';
    import { connect } from 'react-redux';
    import { actions, getBrands } from '../reducer';
    import Infinite from 'react-infinite';
    import InfiniteScroll from 'redux-infinite-scroll';
    import SearchBox from '../components/SearchBox';
    import CardList from '../components/CardList';

    const { fetchBrands } = actions;

    class BrandList extends Component {

        componentDidMount() {
            this.props.fetchBrands({ page: 1 });
        }

        renderList() {
            const brands = this.props.brands;
            return brands.map((brand) => {
                return (
                    <CardList key={brand.id} name={brand.name} avatar={brand.avatar.thumbnail} follower={brand.follows_count} />
                );
            });

        }

        toggle() {
            return this.props.isFetching;
        }

        loadMore() {
            const {lastPage, currentPage} = this.props;
            const nextPage = currentPage ? parseInt(currentPage) + 1 : 1;
            if(currentPage && currentPage <= lastPage){
                this.props.fetchBrands({page: nextPage});
            }
        }

        render() {
            return (
                <div>
                    <SearchBox />

                    <div className="row">
                        <InfiniteScroll
                            items={this.renderList()}
                            loadMore={this.loadMore.bind(this)}
                            elementIsScrollable={false}
                            />
                    </div>
                </div>
            );
        }
    }

    function mapStateToProps(state) {
        return {
            brands: getBrands(state),
            isFetching: state.brand.isFetching,
            currentPage: state.brand.currentPage,
            lastPage: state.brand.lastPage
        };
    }

    export default connect(mapStateToProps, { fetchBrands })(BrandList);

Reducer:

import axios from 'axios';

    // Define Types
    export const types = {
        // brand list
        FETCH_BRANDS: 'fetch_brands',
        FETCH_BRANDS_SUCCESS: 'fetch_brands_success',
        FETCH_BRANDS_ERROR: 'fetch_brands_failure',
        FETCH_BRAND: 'fetch_brand',
        FETCH_BRAND_SUCCESS: 'fetch_brand_success',
        FETCH_BRAND_ERROR: 'fetch_brand_failure',
    };

    const { FETCH_BRANDS, FETCH_BRANDS_SUCCESS, FETCH_BRANDS_ERROR } = types;

    // Define Reducer
    export const INITIAL_STATE = { brands: [], brand: {}, isFetching: false, error: null, currentPage: 1 };

    export default function (state = INITIAL_STATE, action) {
        switch (action.type) {
            case FETCH_BRANDS:
                return { ...state, isFetching: true };
            case FETCH_BRANDS_SUCCESS:
                return { ...state, brands: action.payload.brands.data, currentPage: action.payload.brands.current_page, lastPage: action.payload.brands.last_page };
            case FETCH_BRANDS_ERROR:
                return { ...state, error: action.payload };
            default:
                return state;
        }
    }

    // Define Actions
    export const actions = {
        fetchBrands: ({page, count = 15}) => {
            return (dispatch) => {
                dispatch({ type: FETCH_BRANDS });
                axios.get(`brands?page=${page}&count=${count}`)
                    .then((response) => {
                        const {data} = response;
                        if (data.code == 200) {
                            dispatch({ type: FETCH_BRANDS_SUCCESS, payload: data });
                        }
                    });
            };
        }
    };

    // SELECTOR
    export const getBrands = (state) => state.brand.brands;

1. I inspect element it run next api (page 2) but it not extend current list, it replace it instead.

2. `loadmore` function only run once. it should run 10 times.

Any solution to make it scroll? Or do I miss something on my code?

**Comment by dcurletti** [comment]
1) The ReduxInfiniteScroll page doesn't alter or save any data that is passed to it, you need to properly manage that yourself:

```javascript
case FETCH_BRANDS_SUCCESS:
            return { ...state, brands: brands.concat(action.payload.brands.data), currentPage: action.payload.brands.current_page, lastPage: action.payload.brands.last_page };
```

Try that and then let me know what errors you are getting.   You can also reference this page: http://realscout.github.io/redux-infinite-scroll/ and this code: https://github.com/RealScout/redux-infinite-scroll/blob/gh-pages/main.jsx

**Comment by stefensuhat** [comment]
@dcurletti yes It works.

How about question 2? 
First time page is load, it run 2 API instead of 1, and after I scroll to very bottom it won't load anymore.
I've tried set `hasMore:{true}` but it still not load page 3.

How is the threshold works? I've tried set it to 10, 100, 1000 there is no exact difference when it will load the second page.

**Comment by dcurletti** [comment]
Have you looked at this? https://github.com/RealScout/redux-infinite-scroll#important

> If you are using an element as the scrollable component, rather than the window, you MUST pass a fixed height to the containerHeight prop (many issues will be fixed by following this step).

If your element is the one that should listen to the scroll, then you must pass a `containerHeight` value:
```javascript
<InfiniteScroll
                        items={this.renderList()}
                        loadMore={this.loadMore.bind(this)}
                        containerHeight={200}
                        />
``` 

If your element isn't scrollable, and you want to listen to the scrolling of the window, then you need to set `elementIsScrollable` to `false`: 
```javascript
<InfiniteScroll
                        items={this.renderList()}
                        loadMore={this.loadMore.bind(this)}
                        elementIsScrollable={false}
                        />
```

**Comment by stefensuhat** [comment]
@dcurletti I've update my code using`elementIsScrollable={false}`  is still the same

**Comment by dcurletti** [comment]
```javascript
    loadMore() {
        console.warn('test')
        const {lastPage, currentPage} = this.props;
        const nextPage = currentPage ? parseInt(currentPage) + 1 : 1;
        if(currentPage && currentPage <= lastPage){
            this.props.fetchBrands({page: nextPage});
        }
    }
```

Add that your `loadMore` function and then take a screenshot of your console after you scroll the page.

**Comment by stefensuhat** [comment]
Here is the console.warn

![console](https://cloud.githubusercontent.com/assets/10653041/20956986/bfd68e52-bc7f-11e6-8dfa-a9d5c072ebcc.png)

**Comment by dcurletti** [comment]
ok do this:

**Comment by dcurletti** [comment]
```javascript
export const INITIAL_STATE = { brands: [], brand: {}, isFetching: false, error: null, currentPage: 1, hasMore: true };
```

```javascript
case FETCH_BRANDS_SUCCESS:
            const hasMore = action.payload.brands.current_page && action.payload.brands.current_page < action.payload.brands.last_page;
            return { ...state, hasMore: hasMore, brands: state.brands.concat(action.payload.brands.data), currentPage: action.payload.brands.current_page, lastPage: action.payload.brands.last_page };
```

```javascript
function mapStateToProps(state) {
    return {
        hasMore: state.brand.hasMore,
        brands: getBrands(state),
        isFetching: state.brand.isFetching,
        currentPage: state.brand.currentPage,
        lastPage: state.brand.lastPage
    };
}
```

```javascript
    loadMore() {
        const {lastPage, currentPage} = this.props;
        const nextPage = currentPage ? parseInt(currentPage) + 1 : 1;
        this.props.fetchBrands({page: nextPage});
    }
```

```javascript
<InfiniteScroll
                        items={this.renderList()}
                        loadMore={this.loadMore.bind(this)}
                        elementIsScrollable={false}
                        hasMore={this.props.hasMore}
                        />
```

**Comment by stefensuhat** [comment]
![network](https://cloud.githubusercontent.com/assets/10653041/20957335/d4bc8252-bc81-11e6-9a98-863d619b9e82.png)

Looks like it should work, but at first load it always run page 1 and page 2 together and make page 2 become error (react error because of same key). I've tried set the threshold but no luck.

**Comment by dcurletti** [comment]
```javascript
<InfiniteScroll
                        items={this.renderList()}
                        loadMore={this.loadMore.bind(this)}
                        elementIsScrollable={false}
                        hasMore={this.props.hasMore}
                        isLoadingMore={this.props.isFetching}
                        />
```

```javascript
case FETCH_BRANDS_SUCCESS:
            const hasMore = action.payload.brands.current_page && action.payload.brands.current_page < action.payload.brands.last_page;
            return { ...state, isFetching: false, hasMore: hasMore, brands: state.brands.concat(action.payload.brands.data), currentPage: action.payload.brands.current_page, lastPage: action.payload.brands.last_page };
```

**Comment by stefensuhat** [comment]
Thanks a lot for your help. 

Right now I still try to find out why every time I load the page, it request all pages together without scroll anything.

But you help a lot!. Thanks.

**Comment by dcurletti** [comment]
So after you added the 'isLoadingMore' you are now getting all the pages, as opposed to just the first two?
